# Generated by Django 3.2.7 on 2021-09-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('T_id', models.IntegerField(primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=100)),
                ('L_name', models.CharField(max_length=100)),
                ('Sallary', models.IntegerField(default=10000)),
                ('Join_date', models.DateField(default=2007)),
                ('Mobile_no', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
