# Generated by Django 3.2.7 on 2021-09-17 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('S_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('F_name', models.CharField(max_length=100)),
                ('L_name', models.CharField(max_length=30)),
                ('Class', models.CharField(choices=[('first', 'First'), ('second', 'Second'), ('third', 'Third'), ('fourth', 'Fourth'), ('fifth', 'Fifth'), ('sixth', 'Sixth'), ('seventh', 'Seventh'), ('eighth', 'Eighth'), ('ninth', 'Ninth'), ('tenth', 'Tenth')], default='One', max_length=30)),
                ('Contact', models.CharField(default=0, max_length=100)),
                ('T_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='school.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=2007)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='Present', max_length=30)),
                ('S_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='school.student')),
                ('T_id', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='school.teacher')),
            ],
        ),
    ]
