# Generated by Django 3.2.7 on 2021-09-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_student_s_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='Aroodha10@123', max_length=30),
        ),
    ]
