# Generated by Django 3.2.7 on 2021-09-20 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='T_id',
        ),
    ]
